# All tickers verified against Yahoo Finance (yfinance).
# Format: "Display Name (SYMBOL)": "TICKER.NS / TICKER.BO"

NSE_STOCKS = {
    # ── Banking & Finance ──────────────────────────────────────────────────────
    "HDFC Bank (HDFCBANK)": "HDFCBANK.NS",
    "ICICI Bank (ICICIBANK)": "ICICIBANK.NS",
    "State Bank of India (SBIN)": "SBIN.NS",
    "Axis Bank (AXISBANK)": "AXISBANK.NS",
    "Kotak Mahindra Bank (KOTAKBANK)": "KOTAKBANK.NS",
    "IndusInd Bank (INDUSINDBK)": "INDUSINDBK.NS",
    "Punjab National Bank (PNB)": "PNB.NS",
    "Bank of Baroda (BANKBARODA)": "BANKBARODA.NS",
    "Canara Bank (CANARABANK)": "CANARABANK.NS",
    "Federal Bank (FEDERALBNK)": "FEDERALBNK.NS",
    "IDFC First Bank (IDFCFIRSTB)": "IDFCFIRSTB.NS",
    "Bandhan Bank (BANDHANBNK)": "BANDHANBNK.NS",
    "Bajaj Finance (BAJFINANCE)": "BAJFINANCE.NS",
    "Bajaj Finserv (BAJAJFINSV)": "BAJAJFINSV.NS",
    "HDFC Life Insurance (HDFCLIFE)": "HDFCLIFE.NS",
    "SBI Life Insurance (SBILIFE)": "SBILIFE.NS",
    "ICICI General Insurance (ICICIGI)": "ICICIGI.NS",
    "HDFC AMC (HDFCAMC)": "HDFCAMC.NS",
    "LIC of India (LICI)": "LICI.NS",
    "Muthoot Finance (MUTHOOTFIN)": "MUTHOOTFIN.NS",
    "Cholamandalam Finance (CHOLAFIN)": "CHOLAFIN.NS",
    "REC Limited (RECLTD)": "RECLTD.NS",
    "Power Finance Corporation (PFC)": "PFC.NS",

    # ── IT & Technology ────────────────────────────────────────────────────────
    "Tata Consultancy Services (TCS)": "TCS.NS",
    "Infosys (INFY)": "INFY.NS",
    "Wipro (WIPRO)": "WIPRO.NS",
    "HCL Technologies (HCLTECH)": "HCLTECH.NS",
    "Tech Mahindra (TECHM)": "TECHM.NS",
    "Mphasis (MPHASIS)": "MPHASIS.NS",
    "Persistent Systems (PERSISTENT)": "PERSISTENT.NS",
    "Coforge (COFORGE)": "COFORGE.NS",
    "KPIT Technologies (KPITTECH)": "KPITTECH.NS",
    "Info Edge / Naukri (NAUKRI)": "NAUKRI.NS",

    # ── Oil, Gas & Energy ──────────────────────────────────────────────────────
    "Reliance Industries (RELIANCE)": "RELIANCE.NS",
    "ONGC (ONGC)": "ONGC.NS",
    "BPCL (BPCL)": "BPCL.NS",
    "Coal India (COALINDIA)": "COALINDIA.NS",
    "NTPC (NTPC)": "NTPC.NS",
    "Power Grid Corporation (POWERGRID)": "POWERGRID.NS",
    "Tata Power (TATAPOWER)": "TATAPOWER.NS",
    "Adani Power (ADANIPOWER)": "ADANIPOWER.NS",
    "Adani Green Energy (ADANIGREEN)": "ADANIGREEN.NS",
    "Torrent Power (TORNTPOWER)": "TORNTPOWER.NS",

    # ── Automobiles & Auto Ancillaries ─────────────────────────────────────────
    "Maruti Suzuki (MARUTI)": "MARUTI.NS",
    "Tata Motors (TATAMOTORS)": "TATAMOTORS.NS",
    "Mahindra & Mahindra (M&M)": "M&M.NS",
    "Bajaj Auto (BAJAJ-AUTO)": "BAJAJ-AUTO.NS",
    "Hero MotoCorp (HEROMOTOCO)": "HEROMOTOCO.NS",
    "Eicher Motors (EICHERMOT)": "EICHERMOT.NS",
    "TVS Motor (TVSMOTOR)": "TVSMOTOR.NS",
    "Bosch India (BOSCHLTD)": "BOSCHLTD.NS",
    "Motherson Sumi (MOTHERSON)": "MOTHERSON.NS",
    "Balkrishna Industries (BALKRISIND)": "BALKRISIND.NS",
    "Apollo Tyres (APOLLOTYRE)": "APOLLOTYRE.NS",

    # ── FMCG & Consumer ────────────────────────────────────────────────────────
    "Hindustan Unilever (HINDUNILVR)": "HINDUNILVR.NS",
    "ITC (ITC)": "ITC.NS",
    "Nestle India (NESTLEIND)": "NESTLEIND.NS",
    "Britannia Industries (BRITANNIA)": "BRITANNIA.NS",
    "Dabur India (DABUR)": "DABUR.NS",
    "Marico (MARICO)": "MARICO.NS",
    "Godrej Consumer Products (GODREJCP)": "GODREJCP.NS",
    "Colgate-Palmolive India (COLPAL)": "COLPAL.NS",
    "Emami (EMAMILTD)": "EMAMILTD.NS",
    "Page Industries (PAGEIND)": "PAGEIND.NS",

    # ── Pharma & Healthcare ────────────────────────────────────────────────────
    "Sun Pharmaceutical (SUNPHARMA)": "SUNPHARMA.NS",
    "Cipla (CIPLA)": "CIPLA.NS",
    "Dr. Reddy's Laboratories (DRREDDY)": "DRREDDY.NS",
    "Divi's Laboratories (DIVISLAB)": "DIVISLAB.NS",
    "Lupin (LUPIN)": "LUPIN.NS",
    "Aurobindo Pharma (AUROPHARMA)": "AUROPHARMA.NS",
    "Torrent Pharmaceuticals (TORNTPHARM)": "TORNTPHARM.NS",
    "Zydus Lifesciences (ZYDUSLIFE)": "ZYDUSLIFE.NS",
    "Biocon (BIOCON)": "BIOCON.NS",
    "Alkem Laboratories (ALKEM)": "ALKEM.NS",
    "Abbott India (ABBOTINDIA)": "ABBOTINDIA.NS",
    "Apollo Hospitals (APOLLOHOSP)": "APOLLOHOSP.NS",
    "Max Healthcare (MAXHEALTH)": "MAXHEALTH.NS",
    "Fortis Healthcare (FORTIS)": "FORTIS.NS",

    # ── Metals & Mining ────────────────────────────────────────────────────────
    "Tata Steel (TATASTEEL)": "TATASTEEL.NS",
    "JSW Steel (JSWSTEEL)": "JSWSTEEL.NS",
    "Hindalco Industries (HINDALCO)": "HINDALCO.NS",
    "Vedanta (VEDL)": "VEDL.NS",
    "Hindustan Zinc (HINDZINC)": "HINDZINC.NS",
    "NMDC (NMDC)": "NMDC.NS",
    "SAIL (SAIL)": "SAIL.NS",
    "Jindal Steel & Power (JINDALSTEL)": "JINDALSTEL.NS",

    # ── Infrastructure & Defence ───────────────────────────────────────────────
    "Larsen & Toubro (LT)": "LT.NS",
    "Adani Enterprises (ADANIENT)": "ADANIENT.NS",
    "Adani Ports (ADANIPORTS)": "ADANIPORTS.NS",
    "DLF (DLF)": "DLF.NS",
    "Godrej Properties (GODREJPROP)": "GODREJPROP.NS",
    "Container Corporation (CONCOR)": "CONCOR.NS",
    "Hindustan Aeronautics / HAL (HAL)": "HAL.NS",
    "BEL (BEL)": "BEL.NS",
    "BHEL (BHEL)": "BHEL.NS",
    "IRCTC (IRCTC)": "IRCTC.NS",

    # ── Cement & Building Materials ────────────────────────────────────────────
    "UltraTech Cement (ULTRACEMCO)": "ULTRACEMCO.NS",
    "Ambuja Cements (AMBUJACEM)": "AMBUJACEM.NS",
    "ACC (ACC)": "ACC.NS",
    "Shree Cement (SHREECEM)": "SHREECEM.NS",
    "Grasim Industries (GRASIM)": "GRASIM.NS",
    "Pidilite Industries (PIDILITIND)": "PIDILITIND.NS",
    "Astral (ASTRAL)": "ASTRAL.NS",

    # ── Paints ────────────────────────────────────────────────────────────────
    "Asian Paints (ASIANPAINT)": "ASIANPAINT.NS",
    "Berger Paints (BERGEPAINT)": "BERGEPAINT.NS",

    # ── Consumer Discretionary & Retail ───────────────────────────────────────
    "Titan Company (TITAN)": "TITAN.NS",
    "Trent (TRENT)": "TRENT.NS",
    "Avenue Supermarts / DMart (DMART)": "DMART.NS",
    "Jubilant FoodWorks (JUBLFOOD)": "JUBLFOOD.NS",
    "Bharti Airtel (BHARTIARTL)": "BHARTIARTL.NS",

    # ── New Economy / Digital ──────────────────────────────────────────────────
    "Paytm / One97 (PAYTM)": "PAYTM.NS",
    "Nykaa / FSN E-Commerce (NYKAA)": "NYKAA.NS",
    "PB Fintech / PolicyBazaar (POLICYBZR)": "POLICYBZR.NS",
    "Delhivery (DELHIVERY)": "DELHIVERY.NS",
    "IndiaMART InterMESH (INDIAMART)": "INDIAMART.NS",
    "UPL (UPL)": "UPL.NS",
}

BSE_STOCKS = {
    # ── Banking & Finance ──────────────────────────────────────────────────────
    "HDFC Bank (HDFCBANK)": "HDFCBANK.BO",
    "ICICI Bank (ICICIBANK)": "ICICIBANK.BO",
    "State Bank of India (SBIN)": "SBIN.BO",
    "Axis Bank (AXISBANK)": "AXISBANK.BO",
    "Kotak Mahindra Bank (KOTAKBANK)": "KOTAKBANK.BO",
    "IndusInd Bank (INDUSINDBK)": "INDUSINDBK.BO",
    "Punjab National Bank (PNB)": "PNB.BO",
    "Bank of Baroda (BANKBARODA)": "BANKBARODA.BO",
    "Canara Bank (CANARABANK)": "CANARABANK.BO",
    "Federal Bank (FEDERALBNK)": "FEDERALBNK.BO",
    "IDFC First Bank (IDFCFIRSTB)": "IDFCFIRSTB.BO",
    "Bandhan Bank (BANDHANBNK)": "BANDHANBNK.BO",
    "Bajaj Finance (BAJFINANCE)": "BAJFINANCE.BO",
    "Bajaj Finserv (BAJAJFINSV)": "BAJAJFINSV.BO",
    "Bajaj Holdings (BAJAJHLDNG)": "BAJAJHLDNG.BO",
    "HDFC Life Insurance (HDFCLIFE)": "HDFCLIFE.BO",
    "SBI Life Insurance (SBILIFE)": "SBILIFE.BO",
    "ICICI General Insurance (ICICIGI)": "ICICIGI.BO",
    "HDFC AMC (HDFCAMC)": "HDFCAMC.BO",
    "LIC of India (LICI)": "LICI.BO",
    "Muthoot Finance (MUTHOOTFIN)": "MUTHOOTFIN.BO",
    "Cholamandalam Finance (CHOLAFIN)": "CHOLAFIN.BO",
    "REC Limited (RECLTD)": "RECLTD.BO",
    "Power Finance Corporation (PFC)": "PFC.BO",
    "Sundaram Finance (SUNDARMFIN)": "SUNDARMFIN.BO",
    "Crisil (CRISIL)": "CRISIL.BO",

    # ── IT & Technology ────────────────────────────────────────────────────────
    "Tata Consultancy Services (TCS)": "TCS.BO",
    "Infosys (INFY)": "INFY.BO",
    "Wipro (WIPRO)": "WIPRO.BO",
    "HCL Technologies (HCLTECH)": "HCLTECH.BO",
    "Tech Mahindra (TECHM)": "TECHM.BO",
    "Mphasis (MPHASIS)": "MPHASIS.BO",
    "Persistent Systems (PERSISTENT)": "PERSISTENT.BO",
    "Coforge (COFORGE)": "COFORGE.BO",
    "KPIT Technologies (KPITTECH)": "KPITTECH.BO",
    "Info Edge / Naukri (NAUKRI)": "NAUKRI.BO",

    # ── Oil, Gas & Energy ──────────────────────────────────────────────────────
    "Reliance Industries (RELIANCE)": "RELIANCE.BO",
    "ONGC (ONGC)": "ONGC.BO",
    "BPCL (BPCL)": "BPCL.BO",
    "Coal India (COALINDIA)": "COALINDIA.BO",
    "NTPC (NTPC)": "NTPC.BO",
    "Power Grid Corporation (POWERGRID)": "POWERGRID.BO",
    "Tata Power (TATAPOWER)": "TATAPOWER.BO",
    "Adani Power (ADANIPOWER)": "ADANIPOWER.BO",
    "Adani Green Energy (ADANIGREEN)": "ADANIGREEN.BO",
    "Torrent Power (TORNTPOWER)": "TORNTPOWER.BO",

    # ── Automobiles & Auto Ancillaries ─────────────────────────────────────────
    "Maruti Suzuki (MARUTI)": "MARUTI.BO",
    "Tata Motors (TATAMOTORS)": "TATAMOTORS.BO",
    "Mahindra & Mahindra (M&M)": "M&M.BO",
    "Bajaj Auto (BAJAJ-AUTO)": "BAJAJ-AUTO.BO",
    "Hero MotoCorp (HEROMOTOCO)": "HEROMOTOCO.BO",
    "Eicher Motors (EICHERMOT)": "EICHERMOT.BO",
    "TVS Motor (TVSMOTOR)": "TVSMOTOR.BO",
    "Bosch India (BOSCHLTD)": "BOSCHLTD.BO",
    "Motherson Sumi (MOTHERSON)": "MOTHERSON.BO",
    "Balkrishna Industries (BALKRISIND)": "BALKRISIND.BO",
    "Apollo Tyres (APOLLOTYRE)": "APOLLOTYRE.BO",

    # ── FMCG & Consumer ────────────────────────────────────────────────────────
    "Hindustan Unilever (HINDUNILVR)": "HINDUNILVR.BO",
    "ITC (ITC)": "ITC.BO",
    "Nestle India (NESTLEIND)": "NESTLEIND.BO",
    "Britannia Industries (BRITANNIA)": "BRITANNIA.BO",
    "Dabur India (DABUR)": "DABUR.BO",
    "Marico (MARICO)": "MARICO.BO",
    "Godrej Consumer Products (GODREJCP)": "GODREJCP.BO",
    "Colgate-Palmolive India (COLPAL)": "COLPAL.BO",
    "Emami (EMAMILTD)": "EMAMILTD.BO",
    "Page Industries (PAGEIND)": "PAGEIND.BO",

    # ── Pharma & Healthcare ────────────────────────────────────────────────────
    "Sun Pharmaceutical (SUNPHARMA)": "SUNPHARMA.BO",
    "Cipla (CIPLA)": "CIPLA.BO",
    "Dr. Reddy's Laboratories (DRREDDY)": "DRREDDY.BO",
    "Divi's Laboratories (DIVISLAB)": "DIVISLAB.BO",
    "Lupin (LUPIN)": "LUPIN.BO",
    "Aurobindo Pharma (AUROPHARMA)": "AUROPHARMA.BO",
    "Torrent Pharmaceuticals (TORNTPHARM)": "TORNTPHARM.BO",
    "Zydus Lifesciences (ZYDUSLIFE)": "ZYDUSLIFE.BO",
    "Biocon (BIOCON)": "BIOCON.BO",
    "Alkem Laboratories (ALKEM)": "ALKEM.BO",
    "Abbott India (ABBOTINDIA)": "ABBOTINDIA.BO",
    "3M India (3MINDIA)": "3MINDIA.BO",
    "Apollo Hospitals (APOLLOHOSP)": "APOLLOHOSP.BO",
    "Max Healthcare (MAXHEALTH)": "MAXHEALTH.BO",
    "Fortis Healthcare (FORTIS)": "FORTIS.BO",

    # ── Metals & Mining ────────────────────────────────────────────────────────
    "Tata Steel (TATASTEEL)": "TATASTEEL.BO",
    "JSW Steel (JSWSTEEL)": "JSWSTEEL.BO",
    "Hindalco Industries (HINDALCO)": "HINDALCO.BO",
    "Vedanta (VEDL)": "VEDL.BO",
    "Hindustan Zinc (HINDZINC)": "HINDZINC.BO",
    "NMDC (NMDC)": "NMDC.BO",
    "SAIL (SAIL)": "SAIL.BO",
    "Jindal Steel & Power (JINDALSTEL)": "JINDALSTEL.BO",

    # ── Infrastructure & Defence ───────────────────────────────────────────────
    "Larsen & Toubro (LT)": "LT.BO",
    "Adani Enterprises (ADANIENT)": "ADANIENT.BO",
    "Adani Ports (ADANIPORTS)": "ADANIPORTS.BO",
    "DLF (DLF)": "DLF.BO",
    "Godrej Properties (GODREJPROP)": "GODREJPROP.BO",
    "Container Corporation (CONCOR)": "CONCOR.BO",
    "Hindustan Aeronautics / HAL (HAL)": "HAL.BO",
    "BEL (BEL)": "BEL.BO",
    "BHEL (BHEL)": "BHEL.BO",
    "IRCTC (IRCTC)": "IRCTC.BO",

    # ── Cement & Building Materials ────────────────────────────────────────────
    "UltraTech Cement (ULTRACEMCO)": "ULTRACEMCO.BO",
    "Ambuja Cements (AMBUJACEM)": "AMBUJACEM.BO",
    "ACC (ACC)": "ACC.BO",
    "Shree Cement (SHREECEM)": "SHREECEM.BO",
    "Grasim Industries (GRASIM)": "GRASIM.BO",
    "Pidilite Industries (PIDILITIND)": "PIDILITIND.BO",
    "Astral (ASTRAL)": "ASTRAL.BO",

    # ── Paints ────────────────────────────────────────────────────────────────
    "Asian Paints (ASIANPAINT)": "ASIANPAINT.BO",
    "Berger Paints (BERGEPAINT)": "BERGEPAINT.BO",

    # ── Consumer Discretionary & Retail ───────────────────────────────────────
    "Titan Company (TITAN)": "TITAN.BO",
    "Trent (TRENT)": "TRENT.BO",
    "Avenue Supermarts / DMart (DMART)": "DMART.BO",
    "Jubilant FoodWorks (JUBLFOOD)": "JUBLFOOD.BO",
    "Bharti Airtel (BHARTIARTL)": "BHARTIARTL.BO",

    # ── New Economy / Digital ──────────────────────────────────────────────────
    "Paytm / One97 (PAYTM)": "PAYTM.BO",
    "Nykaa / FSN E-Commerce (NYKAA)": "NYKAA.BO",
    "PB Fintech / PolicyBazaar (POLICYBZR)": "POLICYBZR.BO",
    "Delhivery (DELHIVERY)": "DELHIVERY.BO",
    "IndiaMART InterMESH (INDIAMART)": "INDIAMART.BO",
    "UPL (UPL)": "UPL.BO",
}
